name: opt-params
on:
  workflow_dispatch:
    inputs:
      timeout:
        required: true
        default: "600"
jobs:
  opt-params:
    runs-on: windows-2019
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable
      - name: Build main.rs
        run: cargo build --release
      - name: Generate Testcases
        run: cd tools && .\gen.exe seeds.txt
      - name: Setup | Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Setup | Optuna
        run: python -m pip install optuna
      - name: run
        run: |
          python opt.py ${{ github.event.inputs.timeout }}
          git config user.name  "soraiemame"
          git config user.email "funasou46@yahoo.co.jp"
          git add .
          git commit -m "opt from github actions"
          git push
